name: dadi-ml
channels:
  - conda-forge
  - bioconda
dependencies:
  - codecov
  - gcc
  - gfortran
  - matplotlib
  - numpy
  - pip
  - pytest-cov
  - python==3.8
  - scipy
  - setuptools==58.0.4
  - snakemake==7.1.1
  - mapie=0.3.1
  - scikit-learn=1.0.2
  - pip:
      - git+https://github.com/lntran26/dadi-ml.git@dem-models-update
      - .
