name: dadi-ml
channels:
  - conda-forge
  - bioconda
dependencies:
  - codecov
  - gfortran
  - matplotlib
  - numpy
  - nlopt
  - pip
  - pytest
  - pytest-cov
  - flake8
  - python==3.9.5
  - scipy
  - setuptools==58.0.4
  - snakemake==7.1.1
  - mapie=0.3.1
  - scikit-learn=1.0.2
  - pip:
      - git+https://bitbucket.org/gutenkunstlab/dadi@devel
      - .
