name: donni
channels:
  - conda-forge
dependencies:
  - python=3.9
  - scikit-learn=1.2.0
  - mapie=0.6.1
  - python-irodsclient=1.1.6
  - appdirs=1.4.4
  - pytest
  - pytest-cov
  - codecov
  - gfortran
  - pip
  - dadi
  - dadi-cli
  - pip:
    - .