name: donni
channels:
  - conda-forge
dependencies:
  - python==3.11.*
  - matplotlib
  - scipy
  - numpy
  - python-irodsclient=1.1.6
  - appdirs=1.4.4
  - pytest
  - pytest-cov
  - codecov
  - pip>=19.0
  - dadi
  - dadi-cli
  - pip:
    - .
    - tensorflow==2.12.*
    - keras-tuner==1.4.6
    - mapie
