name: donni
channels:
  - conda-forge
dependencies:
  - python
  - matplotlib
  - scipy
  - numpy
  - python-irodsclient=1.1.6
  - appdirs=1.4.4
  - pytest
  - pytest-cov
  - codecov
  - pip
  - dadi
  - dadi-cli
  - pip:
    - .
    - tensorflow==2.12.*
    - keras-tuner
