name: donni
channels:
  - conda-forge
dependencies:
  - python=3.9
  - scikit-learn=1.2.0
  - mapie=0.6.1
  - matplotlib
  - numpy
  - scipy
  - nlopt
  - pytest
  - gfortran
  - pip
  - pip:
    - git+https://github.com/xin-huang/dadi-cli
    - git+https://bitbucket.org/gutenkunstlab/dadi
    - .