name: build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add micromamba to system path
      uses: mamba-org/setup-micromamba@main
      with:
        environment-name: donni
        activate-environment: donni
        environment-file: environment.yml
    - name: Test with pytest
      run: |
        micromamba run -n donni pytest --cov=. --cov-report term-missing -vv tests/test_*.py
        micromamba run -n donni coverage xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        name: codecov-umbrella
        fail_ci_if_error: true
        env_vars: OS,PYTHON
