name: build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add micromamba to system path
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-name: dadi-ml
        activate-environment: dadi-ml
        environment-file: conda-env.yml
    - name: Test with pytest
      run: |
        cd tests
        micromamba run -n dadi-ml pytest -xv --flake8 *.py

